/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.10.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as clubs from "../clubs.js";
import type * as comments from "../comments.js";
import type * as files from "../files.js";
import type * as follows from "../follows.js";
import type * as likes from "../likes.js";
import type * as posts from "../posts.js";
import type * as saves from "../saves.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  clubs: typeof clubs;
  comments: typeof comments;
  files: typeof files;
  follows: typeof follows;
  likes: typeof likes;
  posts: typeof posts;
  saves: typeof saves;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
