/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as clubguests from "../clubguests.js";
import type * as clubhouseguests from "../clubhouseguests.js";
import type * as clubhouses from "../clubhouses.js";
import type * as clubs from "../clubs.js";
import type * as comments from "../comments.js";
import type * as files from "../files.js";
import type * as follows from "../follows.js";
import type * as likes from "../likes.js";
import type * as posts from "../posts.js";
import type * as saves from "../saves.js";
import type * as users from "../users.js";
import type * as waitings from "../waitings.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  clubguests: typeof clubguests;
  clubhouseguests: typeof clubhouseguests;
  clubhouses: typeof clubhouses;
  clubs: typeof clubs;
  comments: typeof comments;
  files: typeof files;
  follows: typeof follows;
  likes: typeof likes;
  posts: typeof posts;
  saves: typeof saves;
  users: typeof users;
  waitings: typeof waitings;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
